version: "3"
services:
  quotesclient:
    image: jayasurya5454/quotereactclient:latest
    ports:
      - "80:8080"
  quotesserver:
    image: jayasurya5454/quotereactserver:latest
    ports:
      - "5000:5000"
  quotes-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - quotes-db:/data/db

volumes:
  quotes-db: